apiVersion: v1
kind: Pod
metadata:
  name: frontend-backend-pod
  labels:
    app: frontend-backend
spec:
  containers:
  - name: frontend
    imagePullPolicy: Always
    image: shan20000/angular:frontend-${BUILD_NUMBER}
    ports:
    - containerPort: 80
  - name: backend
    imagePullPolicy: Always
    image: shan20000/angular:backend-${BUILD_NUMBER}
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-backend # This should match the labels in the pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: frontend-backend # This should match the labels in the pod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
